version: '3.8'

services:
  imageproxy:
    image: willnorris/imageproxy:latest@sha256:7e4c77d1b64db9152591dbfd8565d5d377eb8a243040efa4e241b97ba94feb1d
    ports:
      - published: ${IMAGEPROXY_PORT}
        target: 8080
    environment:
      IMAGEPROXY_CACHE: redis://imageproxy-redis:6379

  imageproxy-redis:
    image: redis:6@sha256:eff56acc5fc7b909183da93236ba09d3b8cb7d6db31d5b25e9a46dac9b5e699b
    volumes:
      - imageproxy-redis-data:/data

  redis:
    image: redis:6@sha256:eff56acc5fc7b909183da93236ba09d3b8cb7d6db31d5b25e9a46dac9b5e699b
    ports:
      - published: ${REDIS_PORT}
        target: 6379
    volumes:
      - redis-data:/data

volumes:
  imageproxy-redis-data:
  redis-data:
