version: '3.8'

services:
  imageproxy:
    image: willnorris/imageproxy:latest@sha256:7e4c77d1b64db9152591dbfd8565d5d377eb8a243040efa4e241b97ba94feb1d
    ports:
      - published: ${IMAGEPROXY_PORT}
        target: 8080
    environment:
      IMAGEPROXY_CACHE: redis://imageproxy-redis:6379

  imageproxy-redis:
    image: redis:6@sha256:7c540ceff53f0522f6b1c264d8142df08316173d103586ddf51ed91ca49deec8
    volumes:
      - imageproxy-redis-data:/data

  redis:
    image: redis:6@sha256:7c540ceff53f0522f6b1c264d8142df08316173d103586ddf51ed91ca49deec8
    ports:
      - published: ${REDIS_PORT}
        target: 6379
    volumes:
      - redis-data:/data

volumes:
  imageproxy-redis-data:
  redis-data:
