version: '3.8'

services:
  imageproxy:
    image: willnorris/imageproxy:latest
    ports:
      - published: ${IMAGEPROXY_PORT}
        target: 8080
    environment:
      IMAGEPROXY_CACHE: redis://imageproxy-redis:6379

  imageproxy-redis:
    image: redis:6@sha256:f29bcfb891678a0c6a0fc5da0b32ce1ac685af87c0f3aa9327e562da8d3f3b88
    volumes:
      - imageproxy-redis-data:/data

  redis:
    image: redis:6@sha256:f29bcfb891678a0c6a0fc5da0b32ce1ac685af87c0f3aa9327e562da8d3f3b88
    ports:
      - published: ${REDIS_PORT}
        target: 6379
    volumes:
      - redis-data:/data

volumes:
  imageproxy-redis-data:
  redis-data:
