version: '3.8'

services:
  imageproxy:
    image: willnorris/imageproxy
    ports:
      - 8080:8080
    networks:
      - imageproxy
    environment:
      IMAGEPROXY_CACHE: redis://imageproxy-redis:6379

  imageproxy-redis:
    image: redis:6
    networks:
      - imageproxy

  redis:
    image: redis:6
    ports:
      - 6379:6379

networks:
  imageproxy:
    driver: bridge
