version: '3.8'

services:
  imageproxy:
    image: willnorris/imageproxy@sha256:7e4c77d1b64db9152591dbfd8565d5d377eb8a243040efa4e241b97ba94feb1d
    ports:
      - 8080:8080
    networks:
      - imageproxy
    environment:
      IMAGEPROXY_CACHE: redis://imageproxy-redis:6379

  imageproxy-redis:
    image: redis:6@sha256:f29bcfb891678a0c6a0fc5da0b32ce1ac685af87c0f3aa9327e562da8d3f3b88
    networks:
      - imageproxy

  redis:
    image: redis:6@sha256:f29bcfb891678a0c6a0fc5da0b32ce1ac685af87c0f3aa9327e562da8d3f3b88
    ports:
      - 6379:6379

networks:
  imageproxy:
    driver: bridge
